num1 = int(input("What is the first number: "))
num2 = int(input("What is the second number: "))
print("The addition result is: ", num1 + num2)
print("The subtraction result is: ", num1 - num2)
print("The multiplication result is: ", num1 * num2)
print("The division result is: ", num1 / num2)
